//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasefirstapproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepID { get; set; }
        public string DepName { get; set; }
        public string Description { get; set; }
        public int EmployeeEmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
